language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-ci.txt
script:
  - snekchek
after_success:
  - python deploy.py

cache: pip

notifications:
  email:
    on_success: never
    on_failure: never
