language: python
python:
  - "3.6"

branches:
  only:
    - "master"

sudo: required

services:
  - docker

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install pipenv
  - pipenv sync --dev --three
script:
  - pipenv run python -m flake8
after_success:
  - bash scripts/deploy.sh
  # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # - docker build -t pythondiscord/bot:latest .
  # - docker push pythondiscord/bot:latest
  - pipenv run python deploy.py

cache: pip

notifications:
  email: false
